root: true
env:
  browser: true
extends:
  - 'plugin:vue/essential'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2020
rules:
  no-console: 'warn'
  no-debugger: 'warn'
